# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [6]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [10]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [11]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [12]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [3]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [13]:
x.ndim

1

8. Create a boolean array with all the True values

In [25]:
x=np.array((True,True),dtype=bool)
x

array([ True,  True])

9. Create a two dimensional array




In [32]:
x=np.ndarray((3,3))
x

array([[1.04012466e-312, 0.00000000e+000, 1.06395697e+224],
       [1.05935923e+165, 1.39426011e+165, 9.94952853e-047],
       [2.87729783e+180, 3.89694337e-086, 2.42831310e-312]])

10. Create a three dimensional array



In [33]:
x=np.ndarray((3,3,3))
x

array([[[4.11675103e-312, 0.00000000e+000, 1.41537862e+161],
        [6.00736899e-067, 5.38183339e+097, 5.65042639e-038],
        [2.73954041e+126, 3.75598257e+199, 1.57319510e+161]],

       [[7.18974062e-067, 1.29147384e+160, 6.38709031e-067],
        [4.23429343e+175, 3.59751658e+252, 8.93185432e+271],
        [4.76484771e+180, 4.50622287e-144, 7.79952704e-143]],

       [[1.05886701e+165, 5.88973795e-091, 1.05840919e+165],
        [5.24744417e+170, 4.25942251e-096, 7.69165785e+218],
        [1.11763102e+261, 1.16318408e-028, 6.79764291e-310]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [37]:
x = np.array(range(10))
x[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [60]:
x = np.zeros(11)
x[::5] = 1
x

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

13. Create a 3x3 identity matrix

In [59]:
x=np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [70]:
arr=np.array([1,2,3,4,5])
arr = arr.astype('float')
arr.dtype
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [72]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [75]:
arr3 = arr1 == arr2
arr3.all()

False

17. Extract all odd numbers from arr with values(0-9)

In [4]:
arr=np.array(range(0,10))
arr[arr % 2 ==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [6]:
arr[arr % 2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
np.put(arr, [5,6,7], 12)
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [24]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [25]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[arr2d==5]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [29]:
arr2d[0:1:]=64
arr2d

array([[64, 64, 64],
       [ 4, 12,  6],
       [ 7,  8,  9]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [43]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
x[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [42]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
x[1]

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [45]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
x[:,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [63]:
x=np.random.randint(100, size=(10,10))
x
min=np.amax(x)
max=np.amin(x)
print(min)
print(max)

99
0


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int32),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.01755935e+00  5.83256467e-01  1.08144075e-01 -4.02713991e-01]
 [-2.31046138e-01  7.44634850e-01 -5.02725887e-01  3.04176140e+00]
 [-2.70817693e-01  1.75626876e-01  9.53149938e-01  5.35476219e-01]
 [ 8.63110806e-01  5.15790553e-01  3.21344860e-04 -3.77564131e-01]
 [-8.82577451e-01 -1.89430794e+00 -4.21297182e-02  7.55341296e-01]
 [ 1.17524603e+00 -2.02146106e+00 -3.33283473e-01  3.49822211e-02]
 [ 1.42651005e+00  8.31485960e-01 -1.66387333e+00  2.19154456e+00]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [11]:
ar = np.array(range(15)).reshape(5,3)
ar

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [13]:
ar = np.arange(16).reshape(2,2,4)
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

33. Swap axes of the array you created in Question 32

In [16]:
ar.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [25]:
ar = np.arange(10)
print(ar)
ar1 =np.sqrt(ar)
np.where(ar1 < 0.5,0,ar1)


[0 1 2 3 4 5 6 7 8 9]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [36]:
x=np.random.randint(12, size=(12))
y = np.random.randint(12, size=(12))
np.maximum(x, y)

array([ 9,  8,  5,  8,  3,  7, 10,  2,  8,  7,  6,  9])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
(a==b).all()
a = np.setdiff1d(a,b)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [69]:
a = np.array([[34,43,73],[82,22,12],[53,94,66]])
b = np.array([[10,10,10]])

c = np.delete(a, 2, 1)
c=np.append(c, b.transpose(), axis=1)
print(c)


[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [72]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [76]:
x=np.array(np.random.randn(20)*10)
np.cumsum(x)

array([ 15.40599903,  20.62915222,   5.71884758,  -9.48603314,
       -27.9231594 , -30.26006209, -24.3952053 , -34.39012365,
       -36.39414518, -13.39104023,  -1.96271802,  -1.39295762,
        -7.8229708 ,  -9.16495252,   8.01866173,   5.31395109,
        -0.1591806 , -25.81508337, -30.01797244, -21.84028684])